First Pull - Portfolio
Tufahel/portfolio pull request #1
Opened 2022-01-06 13:21 UTC by Tufahel

Portfolio Navbar and header added.

2022-01-06 14:42 UTC, Cathella requested changes
## 🟡 Status: Changes Required 🛑

### Hi @Tufahel 👋🏻, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## The Good points 👏🏻

✔️ No linter errors.
✔️ You used correct Github Flow.
✔️ The sections use the font and colors defined for the template

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- [ ] Please customize your README file to reflect information about the project you are working on
- [ ] Your commit messages do not have a history. As a developer, you document the process of what has transpired while working on your project. This is seen through the commit messages, so just try and make atleast 2 or more commits 🧾

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-06 14:42 UTC, Cathella commented on index.html
> +        </label>
Hi @Tufahel , I can see you are doing a great job on this project 😺.

However for the toolbar, I think you still have a few changes to make 🤔

- [ ] The container of the section is meant to be wrapped in a <header> tag. The header usually contains branding information of a website and the navigation.
- [ ] The logo is also meant to be a link (a tag). This is because is usually clicked on by users to revert back to the homepage. So it would really be nice if it was clickable 😄.
- [ ]  The hamburger button has a `<nav>` tag and I think it would be nice if we followed this structure 👇🏻
```
<header>
  <a href=""> -- logo goes here -- </a>
  <nav>
    <button> -- menu image goes here -- </button>
  </nav>
  <ul>
    <li><a href="#">Home</a></li>
    <li><a href="#">About</a></li>
    <li><a href="#">Contact</a></li>
  </ul>
</header>
```
❓ What do you think about this structure?

2022-01-06 14:42 UTC, Cathella commented on index.html
> +      <img src="images/Header-bg@2x.png" alt="" />
- [ ] This image is meant to be a background image according to the project requirement below 👇🏻 

![image](https://user-images.githubusercontent.com/4247740/148395134-25ac0de3-7a1f-4085-85c5-eb864b1603b5.png)

2022-01-06 14:42 UTC, Cathella commented on index.html
> +        <h1>Great to meet you!!</h1>
- [ ] As per html semantic principles, a page is meant to have only one `<h1>` tag and the rest can be `h2 or h3` or any you choose. If followed, it helps in SEO and google can only pick about the website from an `<h1>` tag. So guess if you find it okay, change the `Great to meet you!!` tag to an appropriate tag 🤔

2022-01-06 14:42 UTC, Cathella commented on index.html
> +          <div class="icon"><img src="images/Vector.png" alt="" /></div>
I can see you did a great job aligning the icons. But think they are presented in a list and it is great that we already have html tags that handle lists. How about we use those?

- [ ] The list of icons uses a `<ul>` tag to group them, and `<li>` per icon; each icon has a link (a tag).
- [ ] In reference to the figma design, I can see that you missed adding the linkedin icon. I think it would be nice if it got added.

2022-01-06 14:42 UTC, Cathella commented on style.css
> +font family. Try this out font-family: 'Crete Round', serif; */
- [ ] I suggest that you try to eliminate blocks of comments in your code. They do make our code unreadable if left around 🤷🏻

2022-01-07 08:34 UTC, Tufahel commented on index.html
> +        </label>
//The container of the section is meant to be wrapped in a tag. The header usually contains branding information of a website and the navigation.//
I don't get this point what you mean. Can you share any references?

2022-01-07 11:33 UTC, Kingstalux requested changes
Hi @Tufahel , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-01-07 11:33 UTC, Kingstalux commented on style.css
> +  background-image: url("images/Header-bg@2x.png");
- [ ] Great job implementing the background image 👍 but there are a couple of background images still missing. Do well to add those and position them well.
- Your design:
![a1](https://user-images.githubusercontent.com/85113567/148536667-9cf7e2c7-45e3-4c21-959c-5616bbe8492d.jpg)
- Figma design:
![a2](https://user-images.githubusercontent.com/85113567/148536805-e1b80c58-acd0-466c-b6f1-da1726addee0.jpg)

2022-01-07 11:33 UTC, Kingstalux commented on index.html
> +          <h1 class="logo"><a href="#">My logo</a></h1>
- [ ] It is better to use a `div` tag around the logo rather than an `h1` tag. `h1` tags are reserved for the heading of our page so it has been used incorrectly in that instance.

2022-01-07 11:33 UTC, Kingstalux commented on index.html
> +          </ul>
- [ ] The hamburger icon should be wrapped in a `nav` tag since it is the navigation button of the mobile website. Also, the logo is not part of the navigation so it should not be in the `nav` tag. Finally, you are only working on the mobile site for now so the desktop links can be taken off as it is not part of the requirements.

2022-01-07 11:33 UTC, Kingstalux commented on README.md
> +LinkedIn: Tufahel Ahmed
- [ ] Your README file looks far better now 👍 but it still lacks some crucial information. It would be nice to add information on how a user can set up your project locally on their machine.

2022-01-07 13:01 UTC, Tufahel commented on style.css
> +  background-image: url("images/Header-bg@2x.png");
Thank you. I have fixed it.

2022-01-07 13:02 UTC, Tufahel commented on index.html
> +          <h1 class="logo"><a href="#">My logo</a></h1>
I have fixed it.

2022-01-07 13:02 UTC, Tufahel commented on README.md
> +LinkedIn: Tufahel Ahmed
Thank you. I have fixed it.

2022-01-07 13:03 UTC, Tufahel commented on index.html
> +          </ul>
Thank you. I have fixed it.

2022-01-07 13:24 UTC, Kingstalux approved these changes
Hi <STUDENT_MENTION>, 
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

Good job implementing the requested changes. Your project is complete!  it's time to merge it :ship: 
Congratulations! 🎉 

_Check the optional comments below and try to implement them in your next project_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-01-07 13:24 UTC, Kingstalux commented on index.html
> +      <h2>I am Tufahel Ahmed <br> Great to meet you!!</h2>
- [ ] (OPTIONAL) This is not really optional but this `h2` tag should be replaced with an `h1` tag for best semantic practices.

2022-01-07 13:24 UTC, Kingstalux commented on index.html
> +      <h1 class="logo"><a href="#">My logo</a></h1>
- [ ] {OPTIONAL) Not really optional too but the `h1` tag here should be replaced by a `div` tag for best semantic practices or you can remove the `h1` tag and simply leave the logo as a link(`a` tag). Logos are usually images and even though the logo here is a word, it should still be placed in a `div` tag.

2022-01-07 13:24 UTC, Kingstalux commented on README.md
> +
- [ ] (OPTIONAL) Your README file is okay for now but you'll need to put in more effort next time to make it look more professional. This [README file ](https://github.com/Kingstalux/React-Capstone/blob/dev/README.md)is an example of a professional README file

2022-01-07 13:47 UTC, merged